// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bdlhqhrnczleonsntnbd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJkbGhxaHJuY3psZW9uc250bmJkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4MDg2MDgsImV4cCI6MjA2MDM4NDYwOH0.aREl_ghMdjrsFt1fYvUvVAzR82SxuNMCUdmH1nqdDwA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);